<?php

namespace Concrete\Package\MdFormResponderNotification;

use Concrete\Core\Express\Controller\Manager;
use Concrete\Core\Package\Package;
use Concrete\Core\Page\Page;
use Concrete\Core\Page\Single;
use Macareux\Package\FormResponderNotification\Express\Controller\AutoResponseController;

class Controller extends Package
{
    protected $pkgHandle = 'md_form_responder_notification';
    protected $appVersionRequired = '8.5.5';
    protected $pkgVersion = '0.1.0';
    protected $pkgAutoloaderRegistries = [
        'src' => '\Macareux\Package\FormResponderNotification',
    ];

    public function getPackageName()
    {
        return t('Macareux Form Responder Notification');
    }

    public function getPackageDescription()
    {
        return t('Send responders a copy of their response.');
    }

    public function on_start()
    {
        $forms = (array) $this->getFileConfig()->get('forms');
        if ($forms) {
            /** @var Manager $manager */
            $manager = $this->app->make(Manager::class);
            foreach ($forms as $handle => $form) {
                $manager->extend($handle, function ($app) {
                    return new AutoResponseController($app);
                });
            }
        }
    }

    public function install()
    {
        $pkg = parent::install(); // TODO: Change the autogenerated stub

        $this->installSinglePages($pkg);

        return $pkg;
    }

    public function upgrade()
    {
        $this->installSinglePages($this->getPackageEntity());

        parent::upgrade();
    }

    private function installSinglePages(\Concrete\Core\Entity\Package $pkg)
    {
        $singlePage = Page::getByPath('/dashboard/system/mail/form_response');
        if (!$singlePage || $singlePage->isError()) {
            $singlePage = Single::add('/dashboard/system/mail/form_response', $pkg);
        }
    }
}